<template>
  <div id="app">
		<h1 class ="slide-in-fwd-center">the PURSUIT of HAPPYNESS</h1>
		<div class="tab_container">
			<input id="tab1" type="radio" name="tabs" checked>
			<label for="tab1"><span>Home</span></label>

			<input id="tab2" type="radio" name="tabs">
			<label for="tab2"><span>Synopsis</span></label>

			<input id="tab3" type="radio" name="tabs">
			<label for="tab3"><span>Videos</span></label>

			<input id="tab4" type="radio" name="tabs">
			<label for="tab4"><span>Gallery</span></label>

			<section id="content1" class="tab-content">
        <h3>Buy Now</h3>
        <div class = "buttons">
		      	<button style = "font-size: 1.5em">On DVD</button> <button style = "font-size: 1.5em">On Blu-Ray</button>
          </div>
        <h3>Follow us</h3>
		      	<div class = "buttons">
            <button><icon name="facebook" scale="2" label="facebook"></icon></button>
            <button><icon name="twitter" scale="2" label="twitter"></icon></button>
            <button><icon name="pinterest" scale="2" label="pinterest"></icon></button>
            <button><icon name="instagram" scale="2" label="instagram"></icon></button>
            </div>
			</section>

			<section id="content2" class="tab-content">
		      	<p>The Pursuit of Happyness is a 2006 American biographical drama film based on entrepreneur Chris Gardner's nearly one-year struggle being homeless. Directed by Gabriele Muccino, the film features Will Smith as Gardner, a homeless salesman. Smith's son Jaden Smith co-stars, making his film debut as Gardner's son, Christopher Jr.</p><p>Life is a struggle for single father Chris Gardner (Will Smith). Evicted from their apartment, he and his young son (Jaden Christopher Syre Smith) find themselves alone with no place to go. Even though Chris eventually lands a job as an intern at a prestigious brokerage firm, the position pays no money. The pair must live in shelters and endure many hardships, but Chris refuses to give in to despair as he struggles to create a better life for himself and his son.</p>
			</section>

			<section id="content3" class="tab-content">
		      	<div style="position:relative;height:0;padding-bottom:56.25%" class = "flip-in-hor-bottom"><iframe src="https://www.youtube.com/embed/89Kq8SDyvfg?ecver=2" width="640" height="360" frameborder="0" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe></div>
			</section>

			<section id="content4" class="tab-content rotate-in-2-cw">
				<Gallery></Gallery>
			</section>

	</div>
  </div>
</template>

<script>
import 'vue-awesome/icons'
import * as Icon from 'vue-awesome'

import Gallery from './gallery.vue'
export default {
  name: 'app',
  data () {
    return {
    }
  },
	components:{
    'icon': Icon,
    Gallery
	}
}
</script>

<style scoped>
.buttons{
  display: flex;
  justify-content: center;
}
button{
  outline: none;
  background: transparent;
  border: 2px solid #fff;
  border-radius: 15px;
  color: #fff;
  padding: 1%;
  margin: 1%;
  transition: background-color 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940);
}
button:hover{
  color: black;
  background-color: #fff;
}
#app{
		font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
    height: 150vh;
  }
*,
*:after,
*:before {
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	box-sizing: border-box;
}

.clearfix:before,
.clearfix:after {
	content: " ";
	display: table;
}

.clearfix:after {
	clear: both;
}

h1 {
	color: white;
	text-align: center;
  font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
  padding-top: 2%;
}

a {
  color: #ccc;
  text-decoration: none;
  outline: none;
}

/*Fun begins*/
.tab_container {
	width: 80%;
	margin: 0 auto;
	padding-top: 40px;
	position: relative;
}

input, section {
  clear: both;
  padding-top: 10px;
  display: none;
}

label {
  display: block;
  float: left;
  width: 25%;
  padding: 1.5em;
  cursor: pointer;
  text-decoration: none;
  text-align: center;
	color: white;
}

/* ----------------------------------------------
 * Generated by Animista on 2017-8-18 19:41:23
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * @animation text-shadow-drop-tl - for label on hover
 * ----------------------------------------
 */
@-webkit-keyframes text-shadow-drop-tl {
  0% {
    text-shadow: 0 0 0 rgba(255,255, 255, 1);
  }
  100% {
    text-shadow: -6px -6px 18px rgba(255,255, 255, 1);
  }
}
@keyframes text-shadow-drop-tl {
  0% {
    text-shadow: 0 0 0 rgba(255,255, 255, 1);
  }
  100% {
    text-shadow: -6px -6px 18px rgba(255, 255,255, 1);
  }
}
.text-shadow-drop-tl, label:hover {
	-webkit-animation: text-shadow-drop-tl 1s both;
	        animation: text-shadow-drop-tl 1s both;
}

#tab1:checked ~ #content1,
#tab2:checked ~ #content2,
#tab3:checked ~ #content3,
#tab4:checked ~ #content4,
#tab5:checked ~ #content5 {
  display: block;
  padding: 20px;
  /*background: #fff;*/
  color: #fff;
  border-bottom: 2px solid #f0f0f0;
}

.tab_container .tab-content p,
.tab_container .tab-content h3 {
  -webkit-animation: fadeInScale 0.7s ease-in-out;
  -moz-animation: fadeInScale 0.7s ease-in-out;
  animation: fadeInScale 0.7s ease-in-out;
}
.tab_container .tab-content h3  {
  text-align: center;
}

.tab_container [id^="tab"]:checked + label {
	-webkit-animation: text-pop-up-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: text-pop-up-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2017-8-18 19:8:44
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-pop-up-top - for label on click
 * ----------------------------------------
 */
@-webkit-keyframes text-pop-up-top {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    text-shadow: none;
  }
  100% {
    -webkit-transform: translateY(-30px);
            transform: translateY(-30px);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc, 0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc, 0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.35);
  }
}
@keyframes text-pop-up-top {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    text-shadow: none;
  }
  100% {
    -webkit-transform: translateY(-30px);
            transform: translateY(-30px);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    /*Use shadows to slowly build up the glow. The first shadow should be the colour of the text. Subsequent shadows are the colour you want the glow to be, all with no x or y offset and with increasing amounts of blur (the number of shadows you use depends on how big you want the glow to be).*/
text-shadow:0 0 10px #fff, 0 0 20px #00d2ff, 0 0 30px #00d2ff, 0 0 40px #00d2ff, 0 0 50px #00d2ff, 0 0 60px #00d2ff, 0 0 70px #00d2ff;
  }
}
.text-pop-up-top{
	-webkit-animation: text-pop-up-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: text-pop-up-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/*Media query*/
@media only screen and (max-width: 930px) {
  label span {
    font-size: 2em;
  }
}

@media only screen and (max-width: 768px) {
  h1{
    padding:3%;
    line-height: 1.5;
  }
  label span {
    font-size: 1.5em;
    padding: 1%;
  }
  .buttons{
    display: flex;
    justify-content: space-around;
    margin:4%;
  }
  .buttons button{
    font-size: 1.6em;
    padding: 3%;
  }
  .tab_container {
    width: 98%;
  }
  .tab-content h3{
    padding-bottom: 3%;
  }
}

/*Content Animation*/
@keyframes fadeInScale {
  0% {
  	transform: scale(0.9);
  	opacity: 0;
  }
  
  100% {
  	transform: scale(1);
  	opacity: 1;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2017-8-23 8:2:50
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-in-hor-bottom - for video 
 * ----------------------------------------
 */
@-webkit-keyframes flip-in-hor-bottom {
  0% {
    -webkit-transform: rotateX(80deg);
            transform: rotateX(80deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
    opacity: 1;
  }
}
@keyframes flip-in-hor-bottom {
  0% {
    -webkit-transform: rotateX(80deg);
            transform: rotateX(80deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
    opacity: 1;
  }
}
.flip-in-hor-bottom {
	-webkit-animation: flip-in-hor-bottom 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: flip-in-hor-bottom 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2017-8-23 22:35:34
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-in-2-cw
 * ----------------------------------------
 */
@-webkit-keyframes rotate-in-2-cw {
  0% {
    -webkit-transform: rotate(-45deg);
            transform: rotate(-45deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
    opacity: 1;
  }
}
@keyframes rotate-in-2-cw {
  0% {
    -webkit-transform: rotate(-45deg);
            transform: rotate(-45deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
    opacity: 1;
  }
}
.rotate-in-2-cw {
	-webkit-animation: rotate-in-2-cw 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: rotate-in-2-cw 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
</style>
